### ISSUE TITLE
请问有没有遇到这个问题 ImportError: cannot import name 'sigmoid_focal_loss_cuda'

### ISSUE THREAD

**Issue by qumj** [OpenFirework/pytorch_solov2#23]
Traceback (most recent call last):
  File "G:/pycharmProject/pytorch_solov2-master/train.py", line 4, in <module>
    from modules.solov2 import SOLOV2
  File "G:\pycharmProject\pytorch_solov2-master\modules\solov2.py", line 6, in <module>
    from .solov2_head import SOLOv2Head
  File "G:\pycharmProject\pytorch_solov2-master\modules\solov2_head.py", line 8, in <module>
    from .focal_loss import FocalLoss
  File "G:\pycharmProject\pytorch_solov2-master\modules\focal_loss.py", line 3, in <module>
    from modules.sigmoid_focal_loss import sigmoid_focal_loss as _sigmoid_focal_loss
  File "G:\pycharmProject\pytorch_solov2-master\modules\sigmoid_focal_loss\__init__.py", line 1, in <module>
    from .sigmoid_focal_loss import SigmoidFocalLoss, sigmoid_focal_loss
  File "G:\pycharmProject\pytorch_solov2-master\modules\sigmoid_focal_loss\sigmoid_focal_loss.py", line 5, in <module>
    from . import sigmoid_focal_loss_cuda
ImportError: cannot import name 'sigmoid_focal_loss_cuda'

**Comment by ABlueLight** [comment]
这是windows下编译的嘛
我没有在windows下验证过，那个编译sigmoid_focal_loss_cuda可能只在Linxu下可以成功
